### ISSUE TITLE
Typescript can't find the types

### ISSUE THREAD

**Issue by TheBosZ** [windsonR/vite-plugin-string-replace#2]
I get this warning when I import the library:

> Could not find a declaration file for module 'vite-plugin-string-replace'. './node_modules/vite-plugin-string-replace/dist/index.mjs' implicitly has an 'any' type.
>   There are types at './node_modules/vite-plugin-string-replace/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vite-plugin-string-replace' library may need to update its package.json or typings

**Comment by windsonR** [comment]
It's weired, cause I have never get this warning when I use this in my vite project.

I've change the `package.json`'s `exports`.So pls use `1.1.2`, it maybe will solve your problem.
If it doesn't work, pls let me know.

**Comment by TheBosZ** [comment]
That worked!
